import { cpSync, existsSync, lstatSync, mkdirSync, symlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import type { LoadedViteWpConfig } from '../config.js';

export function writeWordPressConfig(config: LoadedViteWpConfig) {
  const docroot = resolve(config.root, config.wordpress.docroot);
  const contentDir = resolve(config.root, config.wordpress.contentDir);
  const wpConfigPath = join(docroot, 'wp-config.php');
  const publicUrl = config.wordpress.url;

  mkdirSync(docroot, { recursive: true });
  mkdirSync(join(contentDir, 'plugins'), { recursive: true });
  mkdirSync(join(contentDir, 'mu-plugins'), { recursive: true });
  mkdirSync(join(contentDir, 'uploads'), { recursive: true });
  ensureDefaultContentFiles(contentDir);
  ensureContentSymlink(docroot, contentDir);

  writeFileSync(wpConfigPath, renderWpConfig(config, publicUrl, contentDir), 'utf8');
  console.log(`✓ wp-config.php generated at ${relative(config.root, wpConfigPath)}`);
}

export function phpServerUrl(config: LoadedViteWpConfig) {
  return `http://${config.dev.phpHost}:${config.dev.phpPort}`;
}

function renderWpConfig(config: LoadedViteWpConfig, publicUrl: string, contentDir: string) {
  const database = config.database;

  return `<?php
/**
 * Generated by ViteWP for local development.
 * Do not edit this file by hand; update vitewp.config.ts or environment variables instead.
 */

define('DB_NAME', ${phpString(database.name)});
define('DB_USER', ${phpString(database.user)});
define('DB_PASSWORD', ${phpString(database.password)});
define('DB_HOST', ${phpString(`${database.host}:${database.port}`)});
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

${authKeys()}

$table_prefix = ${phpString(database.tablePrefix)};

define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', false);
define('WP_DEBUG_LOG', true);
@ini_set('display_errors', '0');
define('WP_ENVIRONMENT_TYPE', 'local');
define('WP_DEFAULT_THEME', 'vitewp');
define('WP_HOME', ${phpString(publicUrl)});
define('WP_SITEURL', ${phpString(publicUrl)});
define('WP_CONTENT_DIR', ${phpString(contentDir)});
define('WP_CONTENT_URL', WP_HOME . '/wp-content');
define('VITEWP_ROOT', ${phpString(config.root)});
define('VITEWP_INTERNAL_SECRET', ${phpString(process.env.VITEWP_INTERNAL_SECRET ?? '')});
define('VITEWP_ASSETS_MANIFEST', ${phpString(join(config.root, config.blocks.outDir, 'vitewp-manifest.json'))});
define('VITEWP_MENUS', ${phpString(JSON.stringify(config.wordpress.menus))});
define('VITEWP_OMIT_DEFAULT_ASSETS', ${config.wordpress.omitDefaultAssets ? 'true' : 'false'});

if (
    (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && str_contains($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https'))
    || (isset($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on')
) {
    $_SERVER['HTTPS'] = 'on';
}
if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
}
if (isset($_SERVER['HTTP_X_FORWARDED_PORT'])) {
    $_SERVER['SERVER_PORT'] = $_SERVER['HTTP_X_FORWARDED_PORT'];
} elseif (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') {
    $_SERVER['SERVER_PORT'] = '443';
}

if (! defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

require_once ABSPATH . 'wp-settings.php';
`;
}

function authKeys() {
  const names = [
    'AUTH_KEY',
    'SECURE_AUTH_KEY',
    'LOGGED_IN_KEY',
    'NONCE_KEY',
    'AUTH_SALT',
    'SECURE_AUTH_SALT',
    'LOGGED_IN_SALT',
    'NONCE_SALT',
  ];

  return names.map((name) => `define('${name}', '${randomBytes(32).toString('base64')}');`).join('\n');
}

function phpString(value: string) {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function ensureContentSymlink(docroot: string, contentDir: string) {
  const link = join(docroot, 'wp-content');

  if (existsSync(link)) {
    if (lstatSync(link).isSymbolicLink()) return;
    return;
  }

  const target = relative(dirname(link), contentDir);
  symlinkSync(target, link, 'dir');
}

function ensureDefaultContentFiles(contentDir: string) {
  const packageContentDir = resolve(dirname(fileURLToPath(import.meta.url)), '../../defaults/wordpress/content');

  copyPackageFile(
    join(packageContentDir, 'mu-plugins/vitewp-bridge.php'),
    join(contentDir, 'mu-plugins/vitewp-bridge.php'),
  );
  copyIfMissing(join(packageContentDir, 'themes/vitewp'), join(contentDir, 'themes/vitewp'));
}

function copyPackageFile(source: string, destination: string) {
  if (!existsSync(source)) return;

  mkdirSync(dirname(destination), { recursive: true });
  cpSync(source, destination);
}

function copyIfMissing(source: string, destination: string) {
  if (existsSync(destination) || !existsSync(source)) return;

  mkdirSync(dirname(destination), { recursive: true });
  cpSync(source, destination, { recursive: true });
}
