// Generated by ViteWP. Do not edit by hand.

import type {
  ArchiveTemplateProps as BaseArchiveTemplateProps,
  PageTemplateProps as BasePageTemplateProps,
  SearchTemplateProps as BaseSearchTemplateProps,
  SingleTemplateProps as BaseSingleTemplateProps,
  TaxonomyTemplateProps as BaseTaxonomyTemplateProps,
} from './templates.js';

export type WpPostType = "post" | "page" | "attachment";
export type WpTaxonomy = "category" | "post_tag";

export type WpRestBaseByPostType = {
  "post": "posts";
  "page": "pages";
  "attachment": "media";
};
export type WpArchiveSlugByPostType = {
  "post": null;
  "page": null;
  "attachment": null;
};
export type WpRestBaseByTaxonomy = {
  "category": "categories";
  "post_tag": "tags";
};

export interface WpRenderedField {
  rendered: string;
  protected?: boolean;
}

export interface WpContentItem<PostType extends WpPostType = WpPostType> {
  id: number;
  slug: string;
  type: PostType;
  link: string;
  title: WpRenderedField;
  content: WpRenderedField;
  excerpt?: WpRenderedField;
  date?: string;
  modified?: string;
}

export interface WpArchiveItem<PostType extends WpPostType = WpPostType> extends WpContentItem<PostType> {}

export type WpPageTemplateProps = Omit<BasePageTemplateProps, 'item' | 'route'> & {
  item: WpContentItem<'page'>;
  route: Omit<BasePageTemplateProps['route'], 'item'> & {
    item: WpContentItem<'page'>;
  };
};

export type WpSingleTemplateProps<PostType extends WpPostType = WpPostType> =
  Omit<BaseSingleTemplateProps, 'postType' | 'item' | 'route'> & {
    postType: PostType;
    item: WpContentItem<PostType>;
    route: Omit<BaseSingleTemplateProps['route'], 'postType' | 'item'> & {
      postType: PostType;
      item: WpContentItem<PostType>;
    };
  };

export type WpArchiveTemplateProps<PostType extends WpPostType = WpPostType> =
  Omit<BaseArchiveTemplateProps, 'postType' | 'items' | 'route'> & {
    postType: PostType;
    items: WpArchiveItem<PostType>[];
    route: Omit<BaseArchiveTemplateProps['route'], 'postType' | 'items'> & {
      postType: PostType;
      items: WpArchiveItem<PostType>[];
    };
  };

export type WpSearchTemplateProps = BaseSearchTemplateProps;

export type WpTaxonomyTemplateProps<Taxonomy extends WpTaxonomy = WpTaxonomy> =
  Omit<BaseTaxonomyTemplateProps, 'taxonomy' | 'route'> & {
    taxonomy: Taxonomy;
    route: Omit<BaseTaxonomyTemplateProps['route'], 'taxonomy'> & {
      taxonomy: Taxonomy;
    };
  };
