import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { loadViteWpConfig } from '../config.js';

interface BridgeTypesResponse {
  postTypes: Array<{
    name: string;
    restBase: string;
    archive: boolean;
    archiveSlug: string | null;
    label: string;
    singularLabel: string;
    taxonomies: string[];
    supports: Record<string, unknown>;
  }>;
  taxonomies: Array<{
    name: string;
    restBase: string;
    label: string;
    objectTypes: string[];
    hierarchical: boolean;
  }>;
}

export async function runTypes() {
  const config = await loadViteWpConfig();
  const schema = await fetchBridgeTypes(config.wordpress.url);
  const output = resolve(config.root, config.types.output);

  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, renderTypes(schema), 'utf8');

  console.log(`✓ Generated WordPress types at ${relative(config.root, output)}`);
}

async function fetchBridgeTypes(baseUrl: string) {
  const url = `${baseUrl.replace(/\/$/, '')}/wp-json/vitewp/v1/types`;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Could not fetch WordPress type metadata from ${url}: ${response.status} ${response.statusText}`);
  }

  return response.json() as Promise<BridgeTypesResponse>;
}

function renderTypes(schema: BridgeTypesResponse) {
  const postTypeUnion = union(schema.postTypes.map((postType) => postType.name));
  const taxonomyUnion = union(schema.taxonomies.map((taxonomy) => taxonomy.name));
  const restBaseMap = objectType(schema.postTypes.map((postType) => [postType.name, stringLiteral(postType.restBase)]));
  const archiveSlugMap = objectType(
    schema.postTypes.map((postType) => [postType.name, postType.archiveSlug ? stringLiteral(postType.archiveSlug) : 'null']),
  );
  const taxonomyRestBaseMap = objectType(schema.taxonomies.map((taxonomy) => [taxonomy.name, stringLiteral(taxonomy.restBase)]));

  return `// Generated by ViteWP. Do not edit by hand.

import type {
  ArchiveTemplateProps as BaseArchiveTemplateProps,
  PageTemplateProps as BasePageTemplateProps,
  SearchTemplateProps as BaseSearchTemplateProps,
  SingleTemplateProps as BaseSingleTemplateProps,
  TaxonomyTemplateProps as BaseTaxonomyTemplateProps,
} from 'vite-wp/wordpress/templates';

export type WpPostType = ${postTypeUnion};
export type WpTaxonomy = ${taxonomyUnion};

export type WpRestBaseByPostType = ${restBaseMap};
export type WpArchiveSlugByPostType = ${archiveSlugMap};
export type WpRestBaseByTaxonomy = ${taxonomyRestBaseMap};

export interface WpRenderedField {
  rendered: string;
  protected?: boolean;
}

export interface WpContentItem<PostType extends WpPostType = WpPostType> {
  id: number;
  slug: string;
  type: PostType;
  link: string;
  title: WpRenderedField;
  content: WpRenderedField;
  excerpt?: WpRenderedField;
  date?: string;
  modified?: string;
}

export interface WpArchiveItem<PostType extends WpPostType = WpPostType> extends WpContentItem<PostType> {}

export type WpPageTemplateProps = Omit<BasePageTemplateProps, 'item' | 'route'> & {
  item: WpContentItem<'page'>;
  route: Omit<BasePageTemplateProps['route'], 'item'> & {
    item: WpContentItem<'page'>;
  };
};

export type WpSingleTemplateProps<PostType extends WpPostType = WpPostType> =
  Omit<BaseSingleTemplateProps, 'postType' | 'item' | 'route'> & {
    postType: PostType;
    item: WpContentItem<PostType>;
    route: Omit<BaseSingleTemplateProps['route'], 'postType' | 'item'> & {
      postType: PostType;
      item: WpContentItem<PostType>;
    };
  };

export type WpArchiveTemplateProps<PostType extends WpPostType = WpPostType> =
  Omit<BaseArchiveTemplateProps, 'postType' | 'items' | 'route'> & {
    postType: PostType;
    items: WpArchiveItem<PostType>[];
    route: Omit<BaseArchiveTemplateProps['route'], 'postType' | 'items'> & {
      postType: PostType;
      items: WpArchiveItem<PostType>[];
    };
  };

export type WpSearchTemplateProps = BaseSearchTemplateProps;

export type WpTaxonomyTemplateProps<Taxonomy extends WpTaxonomy = WpTaxonomy> =
  Omit<BaseTaxonomyTemplateProps, 'taxonomy' | 'route'> & {
    taxonomy: Taxonomy;
    route: Omit<BaseTaxonomyTemplateProps['route'], 'taxonomy'> & {
      taxonomy: Taxonomy;
    };
  };
`;
}

function union(values: string[]) {
  if (values.length === 0) return 'never';
  return values.map(stringLiteral).join(' | ');
}

function objectType(entries: Array<[string, string]>) {
  if (entries.length === 0) return 'Record<string, never>';
  return `{\n${entries.map(([key, value]) => `  ${JSON.stringify(key)}: ${value};`).join('\n')}\n}`;
}

function stringLiteral(value: string) {
  return JSON.stringify(value);
}
