import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { loadViteWpConfig } from '../config.js';

interface BridgeTypesResponse {
  postTypes: Array<{
    name: string;
    restBase: string;
    archive: boolean;
    archiveSlug: string | null;
    label: string;
    singularLabel: string;
    taxonomies: string[];
    supports: Record<string, unknown>;
  }>;
  taxonomies: Array<{
    name: string;
    restBase: string;
    label: string;
    objectTypes: string[];
    hierarchical: boolean;
  }>;
}

export async function runTypes() {
  const config = await loadViteWpConfig();
  const schema = await fetchBridgeTypes(config.wordpress.url);
  const output = resolve(config.root, config.types.output);
  const aliasOutput = resolve(config.root, '.vitewp/types.d.ts');
  const types = renderTypes(schema);

  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, types, 'utf8');

  if (output !== aliasOutput) {
    mkdirSync(dirname(aliasOutput), { recursive: true });
    writeFileSync(aliasOutput, types, 'utf8');
  }

  console.log(`✓ Generated WordPress types at ${relative(config.root, aliasOutput)}`);
}

async function fetchBridgeTypes(baseUrl: string) {
  const url = `${baseUrl.replace(/\/$/, '')}/wp-json/vitewp/v1/types`;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Could not fetch WordPress type metadata from ${url}: ${response.status} ${response.statusText}`);
  }

  return response.json() as Promise<BridgeTypesResponse>;
}

function renderTypes(schema: BridgeTypesResponse) {
  const postTypeUnion = union(schema.postTypes.map((postType) => postType.name));
  const taxonomyUnion = union(schema.taxonomies.map((taxonomy) => taxonomy.name));
  const restBaseMap = objectType(schema.postTypes.map((postType) => [postType.name, stringLiteral(postType.restBase)]));
  const archiveSlugMap = objectType(
    schema.postTypes.map((postType) => [postType.name, postType.archiveSlug ? stringLiteral(postType.archiveSlug) : 'null']),
  );
  const taxonomyRestBaseMap = objectType(schema.taxonomies.map((taxonomy) => [taxonomy.name, stringLiteral(taxonomy.restBase)]));
  const taxonomiesByPostTypeMap = objectType(
    schema.postTypes.map((postType) => [postType.name, union(postType.taxonomies)]),
  );

  return `// Generated by ViteWP. Do not edit by hand.

import 'vite-wp/wordpress';
import type {
  ArchiveTemplateProps as BaseArchiveTemplateProps,
  PageTemplateProps as BasePageTemplateProps,
  SearchTemplateProps as BaseSearchTemplateProps,
  SingleTemplateProps as BaseSingleTemplateProps,
  TaxonomyTemplateProps as BaseTaxonomyTemplateProps,
  WpAdditionalData,
  WpMediaItem,
  WpRenderedField,
} from 'vite-wp/wordpress';

export type {
  AnyTemplateProps,
  ArchiveTemplateProps,
  ArchiveTemplateContext,
  HookFilterResult,
  HookOptions,
  HookRenderResult,
  Hooks,
  AuthContextOptions,
  LayoutTemplateProps,
  LiveCacheHint,
  LiveCollection,
  LiveEntry,
  LiveLoader,
  NotFoundTemplateProps,
  PageTemplateProps,
  PageTemplateContext,
  SearchTemplateProps,
  SearchTemplateContext,
  SingleTemplateProps,
  SingleTemplateContext,
  TaxonomyTemplateProps,
  TaxonomyTemplateContext,
  TemplateContext,
  TemplateContextOptions,
  TemplateRouteInfo,
  TemplateRuntimeProps,
  ViteWpAstroLike,
  WpAdditionalData,
  WpArchivePayload,
  WpAuthContext,
  WpBridgeResolution,
  WpBlockEditProps,
  WpBlockSaveProps,
  WpBlockSettings,
  WpBlockEditor,
  WpComponent,
  WpElement,
  WpGlobal,
  WpMedia,
  WpMediaItem,
  WpMediaSize,
  WpMenu,
  WpMenuCollectionFilter,
  WpMenuEntryFilter,
  WpMenuItem,
  WpMenusPayload,
  WpNonce,
  WpPostCollectionFilter,
  WpPostEntryFilter,
  WpPostTypeLoaderOptions,
  WpRenderedField,
  WpRichTextContentProps,
  WpRichTextProps,
  WpResolvedRoute,
  WpRouteCollectionFilter,
  WpRouteEntryFilter,
  WpCurrentUser,
  WpWooCommerceAuthContext,
  WpWooCommerceCustomer,
  ViteWpRequestContext,
} from 'vite-wp/wordpress';

export type {
  WooAttribute,
  WooCart,
  WooCollection,
  WooCustomer,
  WooProduct,
  WooProductAttribute,
  WooProductBrand,
  WooProductImage,
  WooProductPrices,
  WooProductTerm,
  WooProductVariation,
  WooProductVariationAttribute,
  WooQuery,
  WooReview,
  WooReviewQuery,
} from 'vite-wp/woocommerce';

export type WpPostType = ${postTypeUnion};
export type WpTaxonomy = ${taxonomyUnion};

export type WpRestBaseByPostType = ${restBaseMap};
export type WpArchiveSlugByPostType = ${archiveSlugMap};
export type WpRestBaseByTaxonomy = ${taxonomyRestBaseMap};
export type WpTaxonomiesByPostType = ${taxonomiesByPostTypeMap};

export interface WpTerm<Taxonomy extends WpTaxonomy = WpTaxonomy> {
  id: number;
  termId: number;
  taxonomy: Taxonomy;
  slug: string;
  name: string;
  description: string;
  link: string;
  parent: number;
  count: number;
}

export type WpTaxonomyIdMap<PostType extends WpPostType = WpPostType> = {
  [Taxonomy in WpTaxonomiesByPostType[PostType]]?: number[];
};

export type WpTermMap<PostType extends WpPostType = WpPostType> = {
  [Taxonomy in WpTaxonomiesByPostType[PostType]]?: WpTerm<Taxonomy>[];
};

export type WpContentItem<
  PostType extends WpPostType = WpPostType,
  AdditionalData extends WpAdditionalData = WpAdditionalData,
> = {
  id: number;
  slug: string;
  type: PostType;
  link: string;
  title: WpRenderedField;
  content: WpRenderedField;
  excerpt?: WpRenderedField;
  date?: string;
  modified?: string;
  acf: Record<string, unknown>;
  taxonomies: WpTaxonomyIdMap<PostType>;
  terms: WpTermMap<PostType>;
  featuredMediaId: number;
  featuredMedia: WpMediaItem | null;
} & AdditionalData;

export type WpArchiveItem<
  PostType extends WpPostType = WpPostType,
  AdditionalData extends WpAdditionalData = WpAdditionalData,
> = WpContentItem<PostType, AdditionalData>;

export type WpPageTemplateProps<AdditionalData extends WpAdditionalData = WpAdditionalData> =
  Omit<BasePageTemplateProps, 'acf' | 'item' | 'route'> & AdditionalData & {
  item: WpContentItem<'page', AdditionalData>;
  route: Omit<BasePageTemplateProps['route'], 'item'> & {
    item: WpContentItem<'page', AdditionalData>;
  };
};

export type WpSingleTemplateProps<
  PostType extends WpPostType = WpPostType,
  AdditionalData extends WpAdditionalData = WpAdditionalData,
> =
  Omit<BaseSingleTemplateProps, 'acf' | 'postType' | 'item' | 'route'> & AdditionalData & {
    postType: PostType;
    item: WpContentItem<PostType, AdditionalData>;
    route: Omit<BaseSingleTemplateProps['route'], 'postType' | 'item'> & {
      postType: PostType;
      item: WpContentItem<PostType, AdditionalData>;
    };
  };

export type WpArchiveTemplateProps<
  PostType extends WpPostType = WpPostType,
  AdditionalData extends WpAdditionalData = WpAdditionalData,
> =
  Omit<BaseArchiveTemplateProps, 'postType' | 'items' | 'route'> & {
    postType: PostType;
    items: WpArchiveItem<PostType, AdditionalData>[];
    route: Omit<BaseArchiveTemplateProps['route'], 'postType' | 'items'> & {
      postType: PostType;
      items: WpArchiveItem<PostType, AdditionalData>[];
    };
  };

export type WpSearchTemplateProps = BaseSearchTemplateProps;

export type WpTaxonomyTemplateProps<Taxonomy extends WpTaxonomy = WpTaxonomy> =
  Omit<BaseTaxonomyTemplateProps, 'taxonomy' | 'route'> & {
    taxonomy: Taxonomy;
    route: Omit<BaseTaxonomyTemplateProps['route'], 'taxonomy'> & {
      taxonomy: Taxonomy;
    };
  };
`;
}

function union(values: string[]) {
  if (values.length === 0) return 'never';
  return values.map(stringLiteral).join(' | ');
}

function objectType(entries: Array<[string, string]>) {
  if (entries.length === 0) return 'Record<string, never>';
  return `{\n${entries.map(([key, value]) => `  ${JSON.stringify(key)}: ${value};`).join('\n')}\n}`;
}

function stringLiteral(value: string) {
  return JSON.stringify(value);
}
