// Generated by ViteWP. Do not edit by hand.

export type WpPostType = "post" | "page" | "attachment";
export type WpTaxonomy = "category" | "post_tag";

export type WpRestBaseByPostType = {
  "post": "posts";
  "page": "pages";
  "attachment": "media";
};
export type WpArchiveSlugByPostType = {
  "post": null;
  "page": null;
  "attachment": null;
};
export type WpRestBaseByTaxonomy = {
  "category": "categories";
  "post_tag": "tags";
};

export interface WpRenderedField {
  rendered: string;
  protected?: boolean;
}

export interface WpContentItem<PostType extends WpPostType = WpPostType> {
  id: number;
  slug: string;
  type: PostType;
  link: string;
  title: WpRenderedField;
  content: WpRenderedField;
  excerpt?: WpRenderedField;
  date?: string;
  modified?: string;
}

export interface WpArchiveItem<PostType extends WpPostType = WpPostType> extends WpContentItem<PostType> {}
